
USE DESAFIO


SELECT
    CONVERT(date, DATA_INICIO, 101) AS DATA_REFE,
    COUNT(*) AS QT_CORR,
    SUM(CASE WHEN CATEGORIA = 'NEGOCIO' THEN 1 ELSE 0 END) AS QT_CORR_NEG,
	SUM(CASE WHEN CATEGORIA = 'Pessoal' THEN 1 ELSE 0 END) AS QT_CORR_PESS,
	MAX(CAST(DISTANCIA AS DECIMAL(10,2))) AS VL_MAX_DIST,
    MIN(CAST(DISTANCIA AS DECIMAL(10,2))) AS VL_MIN_DIST,
	AVG(CAST(DISTANCIA AS DECIMAL)) AS VL_AVG_DIST,
	COUNT(CASE WHEN PROPOSITO = 'REUNIÃO' THEN 1 ELSE 0 END) AS QT_CORR_REUNI,
	COUNT(CASE WHEN PROPOSITO = '' AND PROPOSITO <> 'REUNIAO' THEN 1 ELSE 0 END) AS QT_CORR_NAO_REUNI
FROM info_transportes
GROUP BY CONVERT(date, DATA_INICIO, 101), PROPOSITO
ORDER by CONVERT(date, DATA_INICIO, 101)
